apiVersion: v1
kind: Service
metadata:
  name: shopsphere-app-npservice-srv
spec:
  type: NodePort
  selector:
    app: shopsphere-app
  ports:
    - name: shopsphere-app
      protocol: TCP
      port: 8080 # port on the inside of our node (remember: this creates a port starting w/ 3####)
      targetPort: 8080 # port it should map to on our running app (inside a pod)